name: insider

on:
  pull_request:
  push:

jobs:
  insider:
    runs-on: ubuntu-latest
    steps:
      - name: Run Insider
        uses: insidersec/insider-action@e41256c9b563ef5307c2bca048bf5ace289dd025
        with:
            technology: javascript
            target: src
