name: insider
on:
  pull_request:
  push:
jobs:
  insider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Insider
        uses: insidersec/insider-action@3e6ddd98666f076a388baf5195f578d48a891c68
        with:
            technology: javascript
            target: .
