name: insider

on:
  pull_request:
  push:

jobs:
  insider:
    runs-on: ubuntu-latest
    steps:
      - name: Run Insider
        uses: insidersec/insider-action@96421050fa19e81e54312ea5d54c217642fa9c5f
        with:
            technology: javascript
            target: src
