name: insider

on:
  pull_request:
  push:

jobs:
  insider:
    runs-on: ubuntu-latest
    steps:
      - name: Run Insider
        uses: insidersec/insider-action@199908415e7c7d45d53738131dca84bd4cb31f00
        with:
            technology: javascript
            target: src
