name: insider

on:
  pull_request:
  push:

jobs:
  insider:
    runs-on: ubuntu-latest
    steps:
      - name: Run Insider
        uses: insidersec/insider-action@deec6e2ac87101bb4aaacf2885d04c9ee7e99365
        with:
            technology: javascript
            target: src
